#!/bin/bash

find . -type f -print0 | xargs -0 sha1sum | cut -d" " -f1 > sum

readarray -t a < ./sum
size=$(echo "${#a[@]}" 

for i in $(seq 0 $size)
do
var1="${a[$i*2]}${a[$i*2+1]}"
a[i]=$(echo -n $var1 | sha1sum | awk '{print $1}')
done
